#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint media_kit_video_tvos.podspec` to validate before publishing.
#
# Generated by `flutter-tvos plugin port`. License holder: The FlutterTV Authors.
#
Pod::Spec.new do |s|
  s.name             = 'media_kit_video_tvos'
  s.version          = '0.0.1'
  s.summary          = 'tvOS implementation of media_kit_video.'
  s.description      = <<-DESC
tvOS implementation of media_kit_video, the federated platform
package that ships native code targeting Apple tvOS.
                       DESC
  s.homepage         = 'https://github.com/fluttertv/media_kit_video_tvos'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'The FlutterTV Authors' => 'noreply@fluttertv.dev' }
  s.source           = { :path => '.' }
  # Upstream ships TWO implementations under Classes/ — `plugin/` (the real
  # renderer, used when the libmpv libs package is present) and `stub/` (a
  # no-op used when it isn't). Both define MediaKitVideoPlugin.swift, so
  # globbing Classes/**/* pulls in both and Xcode rejects the duplicate
  # filename. We always have the libs package, so take the real one.
  # The mpv C headers must be part of THIS pod's source_files, exactly as
  # upstream does it: CocoaPods then puts them in the module's umbrella header
  # so the pod's own Swift can see mpv_node_list / mpv_render_context and
  # friends. Without them the Swift fails with "cannot find type 'mpv_node_list'".
  #
  # Upstream fetches mpv v0.36 headers with a Makefile at build time; these are
  # copied from the libmpv build we actually link (0.37-era, client API 2.2),
  # which is strictly more correct than pinning an older set.
  s.source_files     = 'Classes/plugin/**/*.swift', 'Headers/**/*.h'
  s.public_header_files = 'Classes/**/*.h'
  s.platform         = :tvos, '13.0'

  # STATIC, deliberately. The Podfile uses `use_frameworks!`, which would make
  # this a DYNAMIC framework — and a dynamic framework has to resolve its own
  # symbols at build time. libmpv is a static archive force-loaded into the APP
  # executable, so a dynamic renderer framework cannot see mpv_render_context_*
  # and fails with undefined symbols. Static means these objects link into the
  # same executable the mpv symbols land in, where they resolve normally.
  s.static_framework = true

  # Pulls the libmpv frameworks (and their search paths) into this pod's
  # build, so the renderer compiles against the same library the app links.
  s.dependency 'media_kit_libs_tvos_video'
  s.swift_version    = '5.0'

  # IMPORTANT: this podspec must not depend on the Flutter CocoaPod. That
  # pod does not declare tvOS support, so adding a dependency on it breaks
  # `pod install` for tvOS consumers. Flutter.framework is resolved via
  # FRAMEWORK_SEARCH_PATHS, populated by the host app's Podfile.
  s.xcconfig         = {
    'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../Flutter"',
    'OTHER_SWIFT_FLAGS'      => '$(inherited) -DTARGET_OS_TV',
    'GCC_PREPROCESSOR_DEFINITIONS' => '"$(inherited)" GL_SILENCE_DEPRECATION COREVIDEO_SILENCE_GL_DEPRECATION',
    'GCC_WARN_INHIBIT_ALL_WARNINGS' => 'YES',
  }
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
