name: Create linux installer

on:
  workflow_dispatch:

jobs:
  setup-and-clone:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python 3.12.7 for ${{ matrix.architecture }}
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y python3.12 python3.12-venv python3.12-dev
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
        python3.12 --version
        pip --version

    - name: Create and Activate Virtual Environment
      run: |
        python3.12 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        echo "Virtual environment setup completed."

    - name: Install PyInstaller in Virtual Environment
      run: |
        source venv/bin/activate
        pip install pyinstaller
        pyinstaller --version

    - name: Install Dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build executable with PyInstaller for ${{ matrix.architecture }}
      run: |
        source venv/bin/activate
        pyinstaller \
          --noconfirm \
          --onedir \
          --console \
          --add-data "debrify/config/config.yaml:debrify/config/" \
          --add-data "debrify/config/error_codes.json:rdapi/" \
          --add-data "debrify/data:debrify/data/" \
          --distpath dist/${{ matrix.architecture }} \
          "debrify/main.py"

    - name: Compress dist/${{ matrix.architecture }}/main/
      run: |
        zip -r debrify-linux-${{ matrix.architecture }}.zip dist/${{ matrix.architecture }}/main/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-main-linux-${{ matrix.architecture }}
        path: debrify-linux-${{ matrix.architecture }}.zip
