name: Setup and Clone Debrify (Mac)

on:
  workflow_dispatch:

jobs:
  setup-and-clone:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [arm64, x86_64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python 3.12.7 and Create Virtual Environment for ${{ matrix.architecture }}
      run: |
        brew update
        brew install python@3.12
        python3.12 -m venv venv
        echo "Python 3.12 installed: $(python3.12 --version)"
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        echo "Virtual environment setup completed."

    - name: Install Git
      run: |
        brew install git
        echo "Git version: $(git --version)"

    - name: Install PyInstaller in Virtual Environment
      run: |
        source venv/bin/activate
        pip install pyinstaller
        pyinstaller --version

    - name: Install Dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build executable with PyInstaller for ${{ matrix.architecture }}
      run: |
        source venv/bin/activate
        pyinstaller \
          --noconfirm \
          --onedir \
          --console \
          --add-data "debrify/config/config.yaml:debrify/config/" \
          --add-data "debrify/config/error_codes.json:rdapi/" \
          --add-data "debrify/data:debrify/data/" \
          --distpath dist/${{ matrix.architecture }} \
          "debrify/main.py"

    - name: Compress dist/${{ matrix.architecture }}/main/
      run: |
        zip -r dist-main-mac-${{ matrix.architecture }}.zip dist/${{ matrix.architecture }}/main/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-main-mac-${{ matrix.architecture }}
        path: dist-main-mac-${{ matrix.architecture }}.zip
