name: Create Windows Installer

on:
  workflow_dispatch:

jobs:
  setup-and-clone:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python 3.12.7 and Create Virtual Environment
      run: |
        choco install python --version=3.12.7 --pre
        python --version
        python -m venv venv
        .\venv\Scripts\activate
        python -m pip install --upgrade pip setuptools wheel
        echo "Virtual environment setup completed."

    - name: Install PyInstaller in Virtual Environment
      run: |
        .\venv\Scripts\activate
        pip install pyinstaller
        pyinstaller --version

    - name: Install Dependencies
      run: |
        .\venv\Scripts\activate
        pip install -r requirements.txt

    - name: Compress Build Output with Maximum Compression
      run: |
        cd dist\${{ matrix.architecture }}
        powershell Compress-Archive -Path * -DestinationPath debrify-windows-${{ matrix.architecture }}.zip -CompressionLevel Optimal

    - name: Create Release and Upload ZIP
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist\${{ matrix.architecture }}\debrify-windows-${{ matrix.architecture }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: windows-${{ matrix.architecture }}-${{ github.run_number }}
        name: "Windows Installer - ${{ matrix.architecture }} - Run #${{ github.run_number }}"
        body: |
          This release contains the Windows installer for the ${{ matrix.architecture }} architecture.
          Build run number: ${{ github.run_number }}
        draft: false
        prerelease: false
